services:
  app:
    build: ./backend
    container_name: reuel_pet_app
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/app/data
    environment:
      # dev / prod
      - SPRING_PROFILES_ACTIVE=dev

  frontend:
    build: ./frontend
    container_name: reuel_pet_frontend
    ports:
      - "3000:80"
    depends_on:
      - app

volumes:
  backend_data: