# Production profile (PostgreSQL)

# Datasource (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d5kh2bur433s73ereapg-a.oregon-postgres.render.com/reuel_pet_shop_postgres_database}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:reuel_pet_shop_postgres_database_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:3NKXP5udgM2CabGYkfCTTVCNHEmlNbAx}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false