abacatepay.api.url=https://api.abacatepay.com/v1
abacatepay.api.key=abc_dev_F5HLDKByfY32WYdWmmM1MqMS
abacatepay.webhook.secret=YOUR_WEBHOOK_SECRET

<<<<<<< HEAD
owner.username=${OWNER_USERNAME:owner}
owner.password=${OWNER_PASSWORD:change-me-now}
=======
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configuração do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuração do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
>>>>>>> 739cb3c92d2a76f75b505a5e38170b8f83d81a56
